import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("mypage", "routes/mypage.tsx"),
  route("developer", "routes/developer.tsx"),
  route("api/health", "routes/api.health.ts"),
  route("api/me", "routes/api.me.ts"),
  route("api/me/photo", "routes/api.me.photo.ts"),
  route("api/verify/send", "routes/api.verify.send.ts"),
  route("api/verify/confirm", "routes/api.verify.confirm.ts"),
  route("api/auth/apple", "routes/api.auth.apple.ts"),
  route("api/auth/apple/callback", "routes/api.auth.apple.callback.ts"),
  route("api/auth/magic/send", "routes/api.auth.magic.send.ts"),
  route("api/auth/magic/verify", "routes/api.auth.magic.verify.ts"),
  route("api/auth/logout", "routes/api.auth.logout.ts"),
  route("api/developer/apps", "routes/api.developer.apps.ts"),
  route("api/developer/apps/:id", "routes/api.developer.apps.$id.ts"),
  route("api/sdk/verify-session", "routes/api.sdk.verify-session.ts"),
  route("api/sdk/verify-key", "routes/api.sdk.verify-key.ts"),
  route("api/sdk/users/:id", "routes/api.sdk.users.$id.ts"),
  route("api/auth/unlink-apple", "routes/api.auth.unlink-apple.ts"),
  route("api/photos/*", "routes/api.photos.$.ts"),
] satisfies RouteConfig;
